/**
 * RSA Module
 * Simulates wrapping the AES symmetric key with an RSA-2048 public key
 * generated by the backend module.
 */
class RSAModule {
    static backendPublicKey = null;
    static backendPrivateKey = null;

    /**
     * Simulates fetching the backend's RSA-2048 public key.
     */
    static async generateBackendKeyPair() {
        const keyPair = await window.crypto.subtle.generateKey(
            {
                name: "RSA-OAEP",
                modulusLength: 2048,
                publicExponent: new Uint8Array([1, 0, 1]),
                hash: "SHA-256"
            },
            true,
            ["encrypt", "decrypt"]
        );
        this.backendPublicKey = keyPair.publicKey;
        this.backendPrivateKey = keyPair.privateKey;
    }

    /**
     * Encrypts the raw AES key using the RSA public key.
     * @param {Uint8Array} rawAesKey 
     * @returns {Promise<Uint8Array>} Encrypted AES key
     */
    static async wrapAESKey(rawAesKey) {
        if (!this.backendPublicKey) {
            await this.generateBackendKeyPair();
        }
        
        const encryptedBuffer = await window.crypto.subtle.encrypt(
            { name: "RSA-OAEP" },
            this.backendPublicKey,
            rawAesKey
        );
        
        return new Uint8Array(encryptedBuffer);
    }
}

window.RSAModule = RSAModule;
