/**
 * RSA Module
 * Simulates wrapping the AES symmetric key with an RSA-2048 public key
 * generated by the backend module.
 */
class RSAModule {
    static backendPublicKey = null;

    /**
     * Converts a PEM string to an ArrayBuffer
     */
    static pemToArrayBuffer(pem) {
        const b64 = pem.replace(/(-----(BEGIN|END) PUBLIC KEY-----|\n|\r)/g, '');
        const binary = window.atob(b64);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {
            bytes[i] = binary.charCodeAt(i);
        }
        return bytes.buffer;
    }

    /**
     * Imports the backend's RSA-2048 public key from PEM format.
     */
    static async importServerPublicKey(pemString) {
        const binaryDerString = this.pemToArrayBuffer(pemString);
        this.backendPublicKey = await window.crypto.subtle.importKey(
            "spki",
            binaryDerString,
            {
                name: "RSA-OAEP",
                hash: "SHA-256"
            },
            true,
            ["encrypt"]
        );
    }

    /**
     * Encrypts the raw AES key using the RSA public key.
     * @param {Uint8Array} rawAesKey 
     * @returns {Promise<Uint8Array>} Encrypted AES key
     */
    static async wrapAESKey(rawAesKey) {
        if (!this.backendPublicKey) {
            throw new Error("Backend public key is missing. Call importServerPublicKey first.");
        }
        
        const encryptedBuffer = await window.crypto.subtle.encrypt(
            { name: "RSA-OAEP" },
            this.backendPublicKey,
            rawAesKey
        );
        
        return new Uint8Array(encryptedBuffer);
    }
}

window.RSAModule = RSAModule;
